# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 15:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_auto_20170902_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=50)),
                ('travelling_from', models.CharField(max_length=50)),
                ('travelling_to', models.CharField(max_length=50)),
                ('distance_travelled', models.CharField(max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
