# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_cabrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabrequest',
            name='booking_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
